from __future__ import annotations

import shutil
import subprocess
import time
import unittest
from pathlib import Path

from autodev.real_delivery_validation import RealDeliveryValidation


TEST_TMP_ROOT = Path(__file__).resolve().parents[1] / ".test-tmp"
_TEMP_RUN_ID = str(time.time_ns())
_TEMP_COUNTER = 0


def temp_root() -> Path:
    global _TEMP_COUNTER
    _TEMP_COUNTER += 1
    TEST_TMP_ROOT.mkdir(exist_ok=True)
    root = TEST_TMP_ROOT / f"real-delivery-{_TEMP_RUN_ID}-{_TEMP_COUNTER}"
    root.mkdir(parents=True, exist_ok=False)
    return root


class RealDeliveryValidationTests(unittest.TestCase):
    @classmethod
    def tearDownClass(cls) -> None:
        if TEST_TMP_ROOT.exists():
            shutil.rmtree(TEST_TMP_ROOT, ignore_errors=True)

    def test_fake_real_delivery_validation_writes_report(self) -> None:
        root = temp_root()
        repo = root / "repo"
        repo.mkdir()
        calls: list[list[str]] = []
        captured_branch = {"name": ""}
        check_calls = {"count": 0}

        def fake_runner(args, *, cwd, capture_output, text, check):
            calls.append(args)
            if args == ["git", "rev-parse", "--show-toplevel"]:
                return subprocess.CompletedProcess(args, 0, str(Path(cwd).resolve()) + "\n", "")
            if args == ["git", "status", "--porcelain", "-uall"]:
                return subprocess.CompletedProcess(args, 0, "", "")
            if args[:4] == ["git", "worktree", "add", "-b"]:
                captured_branch["name"] = args[4]
                target = Path(args[-2])
                target.mkdir(parents=True, exist_ok=True)
                return subprocess.CompletedProcess(args, 0, "", "")
            if args[:3] == ["git", "rev-parse", "--verify"]:
                return subprocess.CompletedProcess(args, 1, "", "not found")
            if args == ["git", "checkout", "-B", captured_branch["name"]]:
                return subprocess.CompletedProcess(args, 0, "", "")
            if args == ["git", "add", "-A"]:
                return subprocess.CompletedProcess(args, 0, "", "")
            if args == ["git", "status", "--short"]:
                return subprocess.CompletedProcess(args, 0, "A  .alchemy-real-delivery-validation.md\n", "")
            if args == ["git", "commit", "-m", "Validate Alchemy real delivery flow"]:
                return subprocess.CompletedProcess(args, 0, "[agent/validation abc123] commit\n", "")
            if args == ["git", "push", "-u", "origin", captured_branch["name"]]:
                return subprocess.CompletedProcess(args, 0, "", "")
            if args == ["git", "rev-parse", "HEAD"]:
                return subprocess.CompletedProcess(args, 0, "abc123\n", "")
            if args == ["gh", "pr", "view", captured_branch["name"], "--json", "url,number,state"]:
                return subprocess.CompletedProcess(args, 1, "", "not found")
            if args == [
                "gh",
                "pr",
                "create",
                "--title",
                "Validate Alchemy real delivery flow",
                "--body",
                "Controlled V2.18 validation PR generated by Alchemy Dev Agent. This PR verifies branch, PR, and CI evidence collection.",
                "--head",
                captured_branch["name"],
                "--base",
                "master",
                "--draft",
            ]:
                return subprocess.CompletedProcess(args, 0, "https://example.test/pr/3\n", "")
            if args == [
                "gh",
                "pr",
                "checks",
                captured_branch["name"],
                "--json",
                "name,state,bucket,workflow,link,completedAt,startedAt",
            ]:
                check_calls["count"] += 1
                if check_calls["count"] == 1:
                    return subprocess.CompletedProcess(args, 8, '[{"name":"CI","bucket":"pending","workflow":"CI"}]\n', "")
                return subprocess.CompletedProcess(args, 0, '[{"name":"CI","bucket":"pass","workflow":"CI"}]\n', "")
            return subprocess.CompletedProcess(args, 0, "", "")

        report = RealDeliveryValidation(runner=fake_runner).run(
            repository_path=repo,
            output_dir=root / "out",
            branch="agent/validation",
            base_branch="master",
            ci_wait_seconds=1,
            ci_poll_interval_seconds=0.01,
            keep_worktree=True,
        )
        payload = report.to_dict()

        self.assertEqual(payload["status"], "passed")
        self.assertEqual(payload["github"]["pull_request_url"], "https://example.test/pr/3")
        self.assertEqual(payload["github"]["ci_status"], "passed")
        self.assertEqual(check_calls["count"], 2)
        self.assertTrue((root / "out" / "real_delivery_validation_report.json").exists())
        self.assertTrue(str(payload["branch"]).startswith("agent/validation-"))
        self.assertIn(["git", "push", "-u", "origin", captured_branch["name"]], calls)


if __name__ == "__main__":
    unittest.main()
